<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="19055" started-at="2019-07-29T09:28:17Z" finished-at="2019-07-29T09:28:36Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="19055" started-at="2019-07-29T09:28:17Z" finished-at="2019-07-29T09:28:36Z">
      <class name="xClubsys.BankPayment">
        <test-method status="PASS" signature="setUp()[pri:0, instance:xClubsys.BankPayment@2643d762]" name="setUp" is-config="true" duration-ms="17617" started-at="2019-07-29T09:28:17Z" finished-at="2019-07-29T09:28:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="BankPayment()[pri:0, instance:xClubsys.BankPayment@2643d762]" name="BankPayment" duration-ms="477" started-at="2019-07-29T09:28:34Z" finished-at="2019-07-29T09:28:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BankPayment -->
        <test-method status="FAIL" signature="tearDown()[pri:0, instance:xClubsys.BankPayment@2643d762]" name="tearDown" is-config="true" duration-ms="767" started-at="2019-07-29T09:28:35Z" finished-at="2019-07-29T09:28:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[java.lang.AssertionError: expected [UBO PAYMENT] but found [UOB PAYMENT]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: java.lang.AssertionError: expected [UBO PAYMENT] but found [UOB PAYMENT]
at org.testng.Assert.fail(Assert.java:96)
at xClubsys.BankPayment.tearDown(BankPayment.java:142)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- xClubsys.BankPayment -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
